version: '3.8'

services:
  mysql:
    image: mysql
    container_name: testMysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: store
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/